### PR TITLE
Issue-30: travis build broken (but says it's passing)

### LINKED ISSUE #30: travis build broken (but says it's passing)
https://travis-ci.org/unicef/magicbox-aggregate-mobility/builds

Expected:
* travis build shows failure when tests aren't run
* travis runs tests and test outcome is reflected in the build result

Actual: 
* build history shows green for some builds but the log for each actually shows an error thrown
* looks like it's having trouble finding the ```spark-shell``` binary

### PR DESCRIPTION
**Pull request by JoachimC**
resolves #30  

Apologies - I've never used Travis before. This seems like a nasty solution - surely there's a better way to install spark-shell and hadoop?

But at least now the tests run and the build now reflects their results

### CODE REVIEW

**Comment by JoachimC** [comment]
also we're now downloading and the hadoop and spark-shell binaries in two different places (three if you count the readme.md instructions for developers). Maybe would be better to consolidate these into one place? maybe an npm task - as we're a node project and I think that would be the intuitive place to find automations?

**Comment by jflory7** [comment]
Oh, weird, it looks like the [build failed](https://travis-ci.org/unicef/magicbox-aggregate-mobility/builds/370166662). @JoachimC, are you able to take another look at this PR?

**Comment by JoachimC** [comment]
hmm that's surprising that the build failed but good that it's accurately reported the fail :)

yes. I'll take a look.

**Comment by JoachimC** [comment]
@mikefab , @jflory7 of course this "always works on my computer". But from the log it looks like it was having trouble creating/writing the processed file/directory. So I've covered that area with ```try```-```catch``` blocks and ```console.error```s so hopefully we'll get a bit more information next time it happens.

**Comment by JoachimC** [comment]
ok it's nearly midnight here - close enough to 'tomorrow' so I've fixed it now 😀

I've assumed it's OK to leave the additional ```try```-```catch```s and console logging in there in case something else goes wrong in this area in the future. Of course let me know if you'd like that stuff removed.

**Comment by mikefab** [comment]
Thanks, @JoachimC!

**Pull request merged**
